### ISSUE TITLE
Crash for experiments using an MQTT network connection

### ISSUE THREAD

**Issue by normanius** [phyphox/phyphox-ios#15] opened 2023-09-23 11:26 UTC
I love your work, thanks to everyone contributing to it!

With recent phyphox versions, it ought to be possible to send data with MQTT to some message broker. This works like a charm, on Android systems.

For ios, however, phyphox crashes immediately after the experiment was loaded. The experiment is displayed for a blink of an eye, but then phyphox crashes. Switching between the "mqtt/json" and "mqtt/csv" services does not make any difference. I can avoid the crash by commenting out the <connection> element in the phyphyx file.

Find a minimal reproducing example attached to this message. I use the phyphox://<download-url> to import add the experiment.

What is the status regarding MQTT for the ios version of phyphox? 

[mqtt_connector.phyphyx.zip](https://github.com/phyphox/phyphox-ios/files/12706305/mqtt_connector.phyphyx.zip)

----

phyphox

Version: 1.1.12
Build: 11156
File format: 1.16

Device
Model: iPhone15,2
Brand: Apple
iOS version: 16.6.1

**Comment by Staacks** [comment] 2023-09-26 15:06
Do you have a deadline on when you need it to be working again for your course? I cannot promise a date for the bugfix release, but I am quite sure that I can set up a public beta for your students to use.

**Comment by normanius** [comment] 2023-09-26 15:38
We planned to use this on Friday and Friday next week. That's certainly a bit short notice for a new release... Would be nice to have the Beta, but don't worry if not. We have fallback options: on Android the experiment seems to be working, and we have also a demo with the app Cedalo.

We just discovered that Phyphox also supports MQTT, and as we have already been using Phyphox to introduce the topic "sensing" last week, we thought that's just beautiful to continue with it.

**Comment by Staacks** [comment] 2023-09-27 08:37
I will try if I can get a test version running later that day. If my suspicion about the cause for the bug is correct, it should be possibe...

**Comment by normanius** [comment] 2023-09-27 21:06
Wow, thank you so much for your effort. I will have a look at this tomorrow and give feedback.

**Comment by normanius** [comment] 2023-09-29 14:43
I can confirm: The problem is fixed for the beta version. We used it today with the students, and everything worked like expected. Thank you for your short notice efforts to resolve this issue.

**Comment by Staacks** [comment] 2023-10-01 18:11
Perfect. Then I will close this issue and the fix will be part of release 1.1.13

**Closed by Staacks** 2023-10-01 18:11 UTC
